# Generated by Django 5.2.2 on 2026-04-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(unique=True, verbose_name='ID de Nodo LoRa')),
                ('zone_name', models.CharField(max_length=100, verbose_name='Nombre de Zona')),
                ('ip_range', models.CharField(blank=True, help_text='Rango de IP asociado (opcional)', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_lora',
            field=models.BooleanField(default=False, verbose_name='Enviado por LoRa'),
        ),
        migrations.AddField(
            model_name='message',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.loranode', verbose_name='Zona de Origen'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.loranode', verbose_name='Zona Asignada'),
        ),
    ]
