# Generated by Django 5.2.2 on 2026-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_loranode_message_is_lora_message_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loranode',
            name='battery_level',
            field=models.IntegerField(default=100, verbose_name='Nivel de Batería %'),
        ),
        migrations.AddField(
            model_name='loranode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='loranode',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Última conexión'),
        ),
    ]
