# Generated by Django 5.2.2 on 2026-05-04 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_loranode_battery_level_loranode_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loranode',
            options={'ordering': ['node_id']},
        ),
        migrations.RemoveField(
            model_name='loranode',
            name='ip_range',
        ),
        migrations.RemoveField(
            model_name='loranode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_lora',
        ),
        migrations.RemoveField(
            model_name='message',
            name='zone',
        ),
        migrations.AddField(
            model_name='loranode',
            name='neighbors_data',
            field=models.TextField(default='[]', verbose_name='Vecinos (JSON)'),
        ),
        migrations.AddField(
            model_name='loranode',
            name='status',
            field=models.CharField(choices=[('online', 'En línea'), ('away', 'Inactivo'), ('offline', 'Desconectado')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_to_node',
            field=models.BooleanField(default=False, verbose_name='Entregado a nodo'),
        ),
        migrations.AddField(
            model_name='message',
            name='destination_node',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nodo destino (0=broadcast)'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Mensaje de emergencia'),
        ),
        migrations.AddField(
            model_name='message',
            name='node_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del nodo LoRa'),
        ),
        migrations.AddField(
            model_name='message',
            name='zone_name',
            field=models.CharField(default='General', max_length=100, verbose_name='Zona del nodo'),
        ),
        migrations.AlterField(
            model_name='loranode',
            name='battery_level',
            field=models.IntegerField(default=100, verbose_name='Batería (%)'),
        ),
        migrations.AlterField(
            model_name='loranode',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Última vez visto'),
        ),
        migrations.AlterField(
            model_name='loranode',
            name='node_id',
            field=models.IntegerField(unique=True, verbose_name='ID del nodo'),
        ),
        migrations.AlterField(
            model_name='loranode',
            name='zone_name',
            field=models.CharField(max_length=100, verbose_name='Zona/Ubicación'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(default='General', max_length=100, verbose_name='Zona/Área'),
        ),
    ]
