# Generated by Django 5.2.2 on 2026-05-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_loranode_options_remove_loranode_ip_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destination_node',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nodo destino (0=broadcast)'),
        ),
    ]
