# Generated by Django 5.2.2 on 2026-05-04 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_destination_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destination_sub_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sub-ID destino'),
        ),
        migrations.AddField(
            model_name='message',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_node_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del nodo actual'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub-ID (ej. X.1)'),
        ),
    ]
